# -*- coding: utf-8 -*-
"""weather_api_call.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRqtuW-7PC5A6o9MlsLic3iNHzRFju_G
"""

import pandas as pd
import requests
import os

pd.set_option("display.max_columns", None)

from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("open_weather_api_key")

covid_19_processed_df = pd.read_csv("covid_19_processed.csv")
cities_df = covid_19_processed_df["capital"]

weather_df = pd.DataFrame()

for city in cities_df:
    city_name = city
    api_key = os.getenv("open_weather_api_key")
    city_name_url = (
        f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}"
    )
    response = requests.get(city_name_url)
    city_name_json = response.json()

    row_df = pd.json_normalize(city_name_json)
    temp_cols = ["name", "main.temp_max", "main.temp_min"]
    temp_df = row_df[temp_cols]

    description_df = pd.json_normalize(city_name_json["weather"])
    combined_df = description_df.join(temp_df)

    weather_df = pd.concat([weather_df, combined_df])

selected_cols = ["name", "description", "main.temp_max", "main.temp_min"]
result_df = weather_df[selected_cols]

print("shape of weather data", result_df.shape)

result_df.to_csv("weather_data.csv", index=False)
