# -*- coding: utf-8 -*-
"""covid_19_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSPiqYwXZorMBAJAjL3TNo_lE0EPK4nu
"""

import pandas as pd
import requests
from pandas.io.json import json_normalize

url = 'https://raw.githubusercontent.com/owid/covid-19-data/refs/heads/master/public/data/latest/owid-covid-latest.json'
response = requests.get(url)
data = response.json()

# result = pd.json_normalize(data)
df = pd.DataFrame(data)
result_df = df.transpose()
result_df

result_df = pd.DataFrame()

for key in data.keys():
    row = data[key]
    row_df = pd.json_normalize(row)
    row_df['country_code'] = key
    result_df = pd.concat([result_df, row_df], ignore_index=True)

assert result_df.shape == (247, 67), "dataframe is incorrect shape"

url_countries = "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/refs/heads/master/json/countries.json"
response_contries = requests.get(url_countries)
raw_data_countries = response_contries.json()
df_countries = pd.json_normalize(raw_data_countries)

df_countries.head()

df_countries = df_countries[["iso3", "capital"]]

merge_df = result_df.merge(df_countries, left_on="country_code", right_on="iso3")

capital_col = merge_df['capital']
type(capital_col)

api_key = '10b1f48cb85d9162776f34a3260e4020'
city_name = "Yangon"

city_name_url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}"
response = requests.get(city_name_url)
city_name_json = response.json()
json_normalize(city_name_json['temp_min'])

